<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2GVCL39" ignored="16" name="regression" tests="52" failures="13" timestamp="2022-07-26T21:15:48 IST" time="165.679" errors="0">
  <testcase name="firstTestCase" time="0.005" classname="annotation.AnnotationCCC"/>
  <testcase name="A" time="0.006" classname="anno.AnnoClass"/>
  <testcase name="A" time="0.008" classname="enable.EnableInTestNG"/>
  <testcase name="method1" time="0.007" classname="enable.SampleClass"/>
  <testcase name="method2" time="0.002" classname="enable.SampleClass"/>
  <testcase name="method4" time="0.001" classname="enable.SampleClass"/>
  <testcase name="B" time="0.001" classname="anno.AnnoClass"/>
  <testcase name="sampleAMethodFromAnnotationInTestNGTwo" time="0.012" classname="annotation.AnnotationInTestNGTwo"/>
  <testcase name="method5" time="0.016" classname="enable.SampleClass"/>
  <testcase name="sampleBMethodFromAnnotationInTestNGTwo" time="0.001" classname="annotation.AnnotationInTestNGTwo"/>
  <testcase name="method3" time="0.003" classname="enable.SampleClass"/>
  <testcase name="sampleTestCase" time="20.858" classname="brockenlink.BrockenLinkClass"/>
  <testcase name="sampleTestCase" time="32.743" classname="brockenlink.BrockenLinkClass2"/>
  <testcase name="sampleTestCase" time="2.294" classname="brockenlink.FindStatusCodeOfLink"/>
  <testcase name="sampleTestCase" time="60.737" classname="screen.cpature.ScreenCaptureClass"/>
  <testcase name="sampleTestCase" time="59.875" classname="brockenlink.BrockenLinkClass4ToolQA2">
    <failure type="org.openqa.selenium.WebDriverException" message="unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.134)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;LAPTOP-D2GVCL39&amp;apos;, ip: &amp;apos;192.168.29.64&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_261&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.134, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: C:\Users\91992\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:55795}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 565d33489f0246ababc4931b607db01e">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.134)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-D2GVCL39', ip: '192.168.29.64', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.134, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: C:\Users\91992\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:55795}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 565d33489f0246ababc4931b607db01e
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:134)
at brockenlink.BrockenLinkClass4ToolQA2.sampleTestCase(BrockenLinkClass4ToolQA2.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sampleTestCase -->
  <testcase name="sampleTestCase" time="63.28" classname="brockenlink.BrockenLinkClass3ToolQA"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.001" classname="dataprovider.annotation.DataProviderClass2"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.001" classname="dataprovider.annotation.DataProviderClass2"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.0" classname="dataprovider.annotation.DataProviderClass2"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.002" classname="dataprovider.annotation.DataProviderClass2"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.001" classname="dataprovider.annotation.DataProviderClass"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.001" classname="dataprovider.annotation.DataProviderClass"/>
  <testcase name="verifyUserCanLoginWithProvidedCredentials2" time="0.001" classname="dataprovider.annotation.DataProviderClass"/>
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.01" classname="dependend.test.cases.DependentTestCasesClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependend.test.cases.DependentTestCasesClass2.verifyUserCanLoginWithValidUserNameAndPassword(DependentTestCasesClass2.java:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="verifyUserCanSendEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass2"/>
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.012" classname="assertions.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User name is not displayed expected [true] but found [false],
	deleted user is displayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User name is not displayed expected [true] but found [false],
deleted user is displayed expected [false] but found [true]
at assertions.SoftAssertionClass.verifyUserCanLoginWithValidUserNameAndPassword(SoftAssertionClass.java:25)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="verifyUserCanReadEmail" time="0.003" classname="assertions.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [null] but found [anno.AnnoClass@75eabd4e]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [null] but found [anno.AnnoClass@75eabd4e]
at assertions.SoftAssertionClass.verifyUserCanReadEmail(SoftAssertionClass.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyUserCanSendEmail" time="0.003" classname="assertions.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	values is not matching expected [45] but found [23]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
values is not matching expected [45] but found [23]
at assertions.SoftAssertionClass.verifyUserCanSendEmail(SoftAssertionClass.java:36)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="assertions.AssertionClass"/>
  <testcase name="verifyUserCanReadEmail" time="0.001" classname="assertions.AssertionClass">
    <failure type="java.lang.AssertionError" message="Current share price is not matching expected [405.55] but found [405.55]">
      <![CDATA[java.lang.AssertionError: Current share price is not matching expected [405.55] but found [405.55]
at assertions.AssertionClass.verifyUserCanReadEmail(AssertionClass.java:45)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyUserCanSendEmail" time="0.0" classname="assertions.AssertionClass">
    <failure type="java.lang.AssertionError" message="expected [null] but found [anno.AnnoClass@55d642b]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [anno.AnnoClass@55d642b]
at assertions.AssertionClass.verifyUserCanSendEmail(AssertionClass.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyuserslist" time="0.011" classname="assertions.AssertionClass">
    <failure type="java.lang.AssertionError" message="expected [45] but found [23]">
      <![CDATA[java.lang.AssertionError: expected [45] but found [23]
at assertions.AssertionClass.verifyuserslist(AssertionClass.java:55)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyuserslist -->
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="dependend.test.cases.DependentTestCasesClass"/>
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="annotation.AnnotationInTestNG"/>
  <testcase name="verifyUserCanReadEmail" time="0.003" classname="annotation.AnnotationInTestNG"/>
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="annotation.AnnotationInTestNG"/>
  <testcase name="verifyUserCanSendEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependend.test.cases.DependentTestCasesClass.verifyUserCanSendEmail(DependentTestCasesClass.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyUserCanReadEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass">
    <skipped/>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="invocation.InvocationCountClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.003" classname="invocation.InvocationCountClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.0" classname="invocation.InvocationCountClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at invocation.InvocationCountClass.verifyUserCanSendEmail(InvocationCountClass.java:16)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyUserCanSendEmail" time="0.004" classname="invocation.InvocationCountClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.007" classname="invocation.InvocationCountClass"/>
  <testcase name="sample" time="0.0" classname="invocation.InvocationCountClass">
    <skipped/>
  </testcase> <!-- sample -->
  <testcase name="verifyNewUserCanBeAddedWithProvidedData" time="0.0" classname="dataprovider.annotation.DataProviderClass3">
    <skipped/>
  </testcase> <!-- verifyNewUserCanBeAddedWithProvidedData -->
  <testcase name="verifyExistingUserCanBeedited" time="0.001" classname="priority.PriorityClass"/>
  <testcase name="verifyExistingUserCanBeDeleted" time="0.0" classname="priority.PriorityClass"/>
  <testcase name="verifyNewUserCanBeadded" time="0.001" classname="priority.PriorityClass"/>
  <testcase name="sampleTestCase" time="103.913" classname="screen.cpature.ScreenCaptureClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at screen.cpature.ScreenCaptureClass2.sampleTestCase(ScreenCaptureClass2.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sampleTestCase -->
  <testcase name="verifyLinksAreBrockenOrNot" time="56.636" classname="brockenlink.BrockenLinkClass5ToolQA3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	https://demoqa.com/bad-request is brcken with status code = 400 expected [true] but found [false],
	https://demoqa.com/unauthorized is brcken with status code = 401 expected [true] but found [false],
	https://demoqa.com/forbidden is brcken with status code = 403 expected [true] but found [false],
	https://demoqa.com/invalid-url is brcken with status code = 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
https://demoqa.com/bad-request is brcken with status code = 400 expected [true] but found [false],
https://demoqa.com/unauthorized is brcken with status code = 401 expected [true] but found [false],
https://demoqa.com/forbidden is brcken with status code = 403 expected [true] but found [false],
https://demoqa.com/invalid-url is brcken with status code = 404 expected [true] but found [false]
at brockenlink.BrockenLinkClass5ToolQA3.verifyLinksAreBrockenOrNot(BrockenLinkClass5ToolQA3.java:57)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyLinksAreBrockenOrNot -->
  <testcase name="verifyfileupload" time="63.588" classname="annotation.FileUploadTestCase">
    <failure type="java.lang.AssertionError" message="expected [1 file has been successfully uploaded.] but found [1 file
has been successfully uploaded.]">
      <![CDATA[java.lang.AssertionError: expected [1 file has been successfully uploaded.] but found [1 file
has been successfully uploaded.]
at annotation.FileUploadTestCase.verifyfileupload(FileUploadTestCase.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyfileupload -->
  <testcase name="B" time="0.0" classname="enable.EnableInTestNG">
    <ignored/>
  </testcase> <!-- B -->
  <testcase name="verifyUserCanLoginWithProvidedCredentials" time="0.0" classname="dataprovider.annotation.DataProviderClass">
    <ignored/>
  </testcase> <!-- verifyUserCanLoginWithProvidedCredentials -->
  <testcase name="@AfterSuite sampleAfterSuiteAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite sampleAfterSuiteAnnotationMethod -->
  <testcase name="@AfterSuite sampleAfterSuiteAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite sampleAfterSuiteAnnotationMethod -->
  <testcase name="@AfterSuite sampleAfterSuiteAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite sampleAfterSuiteAnnotationMethod -->
  <testcase name="verifyuserCanaddDataOnUI" time="0.0" classname="dataprovider.annotation.DataProviderClass">
    <ignored/>
  </testcase> <!-- verifyuserCanaddDataOnUI -->
  <testcase name="@AfterTest sampleAfterTestAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest sampleAfterTestAnnotationMethod -->
  <testcase name="@AfterTest sampleAfterTestAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest sampleAfterTestAnnotationMethod -->
  <testcase name="@AfterTest sampleAfterTestAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest sampleAfterTestAnnotationMethod -->
  <testcase name="@BeforeTest sampleBeforeTestAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest sampleBeforeTestAnnotationMethod -->
  <testcase name="@BeforeTest sampleBeforeTestAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest sampleBeforeTestAnnotationMethod -->
  <testcase name="@BeforeTest sampleBeforeTestAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest sampleBeforeTestAnnotationMethod -->
  <testcase name="verifyUserCanReadEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass2">
    <ignored/>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="@BeforeSuite sampleBeforeSuiteAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite sampleBeforeSuiteAnnotationMethod -->
  <testcase name="@BeforeSuite sampleBeforeSuiteAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite sampleBeforeSuiteAnnotationMethod -->
  <testcase name="@BeforeSuite sampleBeforeSuiteAnnotationMethod" time="0.0" classname="annotation.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite sampleBeforeSuiteAnnotationMethod -->
</testsuite> <!-- regression -->
